spring:
  profiles:
    active: local
  banner:
    location: classpath:banner.txt

# Default server port
server:
  port: 8080

# Default management port
management:
  server:
    port: 8081

scheduling:
  fixedDelayInMilliseconds: 1000
